---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, message=FALSE}
library(tidyverse)
library(p8105.datasets)
library(RColorBrewer)
library(plotly)
library(flexdashboard)
```

```{r message=FALSE, warning=FALSE}
nyc_restaurant = 
  rest_inspec |>
  drop_na() |>
  filter(grade != "NA" & boro != "Missing" & grade != "Not Yet Graded") |>
  mutate(year = year(inspection_date))
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r message=FALSE, warning=FALSE}
nyc_boxplot = 
  nyc_restaurant |>
  ggplot(aes(x = boro, y = score, fill = boro)) +  
  scale_fill_brewer(palette = "Set3") +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Borough", y = "Score", title = "Inspection Score of Restaurants in NYC Boroughs", fill = "Borough")

ggplotly(nyc_boxplot)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r message=FALSE, warning=FALSE}
nyc_barchart = 
  nyc_restaurant |>
  group_by(boro, grade) |>
  summarise(num_per_grade = n()) |>
  pivot_wider(
    names_from = "boro", 
    values_from = "num_per_grade"
  )

colnames(nyc_barchart)[6] <- "STATEN_ISLAND"

nyc_barchart = 
  nyc_barchart |>
  plot_ly(x = ~grade, y = ~BRONX, type = 'bar', name = 'Bronx') |>
  add_trace(y = ~BROOKLYN, name = 'Brooklyn') |>
  add_trace(y = ~MANHATTAN, name = 'Manhattan') |>
  add_trace(y = ~QUEENS, name = 'Queens') |>
  add_trace(y = ~STATEN_ISLAND, name = 'Staten Island') |>
  layout(yaxis = list(title = 'Count'), xaxis = list(title = 'Grade Level'), title = "Number of Restaurants per Grade Level in NYC Boroughs")

nyc_barchart
```

### Chart C

```{r message=FALSE, warning=FALSE}
nyc_lineplot = 
  nyc_restaurant |>
  filter(year==2017) |>
  group_by(boro, inspection_date) |>
  summarise(avg_score = mean(score, na.rm = FALSE)) |>
  pivot_wider(
    names_from = "boro", 
    values_from = "avg_score"
  )

colnames(nyc_lineplot)[6] <- "STATEN_ISLAND"

nyc_lineplot  = 
  nyc_lineplot|>
  drop_na() |>
  plot_ly(x = ~inspection_date, y = ~BRONX, name = 'Bronx', type = 'scatter', mode = 'lines') |>
  add_trace(y = ~BROOKLYN, name = 'Brooklyn', mode = 'lines') |>
  add_trace(y = ~MANHATTAN, name = 'Manhattan', mode = 'lines') |>
  add_trace(y = ~QUEENS, name = 'Queens', mode = 'lines') |>
  add_trace(y = ~STATEN_ISLAND, name = 'Staten Island', mode = 'lines') |>
  layout(yaxis = list(title = 'Average Score'), xaxis = list(title = 'Inspection Date'), title = "Average Restaurant Score by Date in 2017 in NYC Boroughs")

nyc_lineplot
```
